/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyzerConfigUpdateRequest {
    /// Arbitrary JSON object representing a worker's specific configuration.
    #[serde(rename = "config")]
    pub config: std::collections::HashMap<String, serde_json::Value>,
}

impl AnalyzerConfigUpdateRequest {
    pub fn new(config: std::collections::HashMap<String, serde_json::Value>) -> AnalyzerConfigUpdateRequest {
        AnalyzerConfigUpdateRequest {
            config,
        }
    }
}

