/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnalyzerCreateRequest : Fields for creating an analyzer. Specific properties depend on the analyzer's definition and its configurationItems.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyzerCreateRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Arbitrary JSON object representing a worker's specific configuration.
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "dataTypeList", skip_serializing_if = "Option::is_none")]
    pub data_type_list: Option<Vec<String>>,
}

impl AnalyzerCreateRequest {
    /// Fields for creating an analyzer. Specific properties depend on the analyzer's definition and its configurationItems.
    pub fn new() -> AnalyzerCreateRequest {
        AnalyzerCreateRequest {
            name: None,
            configuration: None,
            data_type_list: None,
        }
    }
}

