/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigurationDefinitionItemDefaultValue : Default value for the configuration item.
/// Default value for the configuration item.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigurationDefinitionItemDefaultValue {
    String(String),
    Number(f64),
    Boolean(bool),
}

impl Default for ConfigurationDefinitionItemDefaultValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

