/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbListAddItemRequest {
    /// The JSON value to add to the list.
    #[serde(rename = "value")]
    pub value: std::collections::HashMap<String, serde_json::Value>,
}

impl DbListAddItemRequest {
    pub fn new(value: std::collections::HashMap<String, serde_json::Value>) -> DbListAddItemRequest {
        DbListAddItemRequest {
            value,
        }
    }
}

