/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbListItemExistsRequest {
    #[serde(rename = "key")]
    pub key: String,
    /// The JSON value to check.
    #[serde(rename = "value")]
    pub value: std::collections::HashMap<String, serde_json::Value>,
}

impl DbListItemExistsRequest {
    pub fn new(key: String, value: std::collections::HashMap<String, serde_json::Value>) -> DbListItemExistsRequest {
        DbListItemExistsRequest {
            key,
            value,
        }
    }
}

