/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobStatusRequest {
    /// A list of job IDs to get the status for.
    #[serde(rename = "jobIds")]
    pub job_ids: Vec<String>,
}

impl JobStatusRequest {
    pub fn new(job_ids: Vec<String>) -> JobStatusRequest {
        JobStatusRequest {
            job_ids,
        }
    }
}

