/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobReportResponse {
    Object(serde_json::Value),
    JobReportResponseOneOf(models::JobReportResponseOneOf),
}

impl Default for JobReportResponse {
    fn default() -> Self {
        Self::Object(Default::default())
    }
}

