/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MispQueryResponse : Results from a MISP module query.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MispQueryResponse {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::MispQueryResponseResultsInner>>,
}

impl MispQueryResponse {
    /// Results from a MISP module query.
    pub fn new() -> MispQueryResponse {
        MispQueryResponse {
            results: None,
        }
    }
}

