/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MispQueryRequest {
    /// The name of the Cortex analyzer/module to query.
    #[serde(rename = "module")]
    pub module: String,
}

impl MispQueryRequest {
    pub fn new(module: String) -> MispQueryRequest {
        MispQueryRequest {
            module,
        }
    }
}

