/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MispModuleMispattributes {
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<Vec<String>>,
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<Vec<String>>,
}

impl MispModuleMispattributes {
    pub fn new() -> MispModuleMispattributes {
        MispModuleMispattributes {
            input: None,
            output: None,
        }
    }
}

