/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationFindRequest {
    /// Elastic4Play Query Definition Language object for searches.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<String>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Vec<String>>,
    /// Whether to include statistics in the response.
    #[serde(rename = "nstats", skip_serializing_if = "Option::is_none")]
    pub nstats: Option<bool>,
}

impl OrganizationFindRequest {
    pub fn new() -> OrganizationFindRequest {
        OrganizationFindRequest {
            query: None,
            range: None,
            sort: None,
            nstats: None,
        }
    }
}

