/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationStatsRequest {
    /// Elastic4Play Query Definition Language object for searches.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Aggregation definitions.
    #[serde(rename = "stats")]
    pub stats: Vec<std::collections::HashMap<String, serde_json::Value>>,
}

impl OrganizationStatsRequest {
    pub fn new(stats: Vec<std::collections::HashMap<String, serde_json::Value>>) -> OrganizationStatsRequest {
        OrganizationStatsRequest {
            query: None,
            stats,
        }
    }
}

