/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordChangeRequest {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "currentPassword")]
    pub current_password: String,
}

impl PasswordChangeRequest {
    pub fn new(password: String, current_password: String) -> PasswordChangeRequest {
        PasswordChangeRequest {
            password,
            current_password,
        }
    }
}

