/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponse {
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Box<models::StatusResponseVersions>>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<models::StatusResponseConfig>>,
}

impl StatusResponse {
    pub fn new() -> StatusResponse {
        StatusResponse {
            versions: None,
            config: None,
        }
    }
}

