/*
 * Cortex API
 *
 * API for Cortex, a powerful observable analysis and active response engine.
 *
 * The version of the OpenAPI document: 3.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StreamMessagesResponse : Messages from a stream.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamMessagesResponse {
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Vec<std::collections::HashMap<String, serde_json::Value>>>,
}

impl StreamMessagesResponse {
    /// Messages from a stream.
    pub fn new() -> StreamMessagesResponse {
        StreamMessagesResponse {
            operations: None,
        }
    }
}

